# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sliders.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 791, 551))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 711, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_min = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_min.setObjectName("lb_min")
        self.gridLayout.addWidget(self.lb_min, 1, 1, 1, 1)
        self.lb_r = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_r.setObjectName("lb_r")
        self.gridLayout.addWidget(self.lb_r, 4, 0, 1, 1)
        self.hs_r_max = QtWidgets.QSlider(self.gridLayoutWidget)
        self.hs_r_max.setMaximum(255)
        self.hs_r_max.setOrientation(QtCore.Qt.Horizontal)
        self.hs_r_max.setObjectName("hs_r_max")
        self.gridLayout.addWidget(self.hs_r_max, 4, 2, 1, 1)
        self.hs_r_min = QtWidgets.QSlider(self.gridLayoutWidget)
        self.hs_r_min.setMaximum(255)
        self.hs_r_min.setOrientation(QtCore.Qt.Horizontal)
        self.hs_r_min.setObjectName("hs_r_min")
        self.gridLayout.addWidget(self.hs_r_min, 4, 1, 1, 1)
        self.hs_v_max = QtWidgets.QSlider(self.gridLayoutWidget)
        self.hs_v_max.setMaximum(255)
        self.hs_v_max.setOrientation(QtCore.Qt.Horizontal)
        self.hs_v_max.setObjectName("hs_v_max")
        self.gridLayout.addWidget(self.hs_v_max, 3, 2, 1, 1)
        self.hs_v_min = QtWidgets.QSlider(self.gridLayoutWidget)
        self.hs_v_min.setMaximum(255)
        self.hs_v_min.setOrientation(QtCore.Qt.Horizontal)
        self.hs_v_min.setObjectName("hs_v_min")
        self.gridLayout.addWidget(self.hs_v_min, 3, 1, 1, 1)
        self.hs_b_max = QtWidgets.QSlider(self.gridLayoutWidget)
        self.hs_b_max.setMaximum(255)
        self.hs_b_max.setOrientation(QtCore.Qt.Horizontal)
        self.hs_b_max.setObjectName("hs_b_max")
        self.gridLayout.addWidget(self.hs_b_max, 2, 2, 1, 1)
        self.pb_submit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_submit.setObjectName("pb_submit")
        self.gridLayout.addWidget(self.pb_submit, 5, 1, 1, 1)
        self.pb_enter = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_enter.setObjectName("pb_enter")
        self.gridLayout.addWidget(self.pb_enter, 5, 2, 1, 1)
        self.hs_b_min = QtWidgets.QSlider(self.gridLayoutWidget)
        self.hs_b_min.setMaximum(255)
        self.hs_b_min.setOrientation(QtCore.Qt.Horizontal)
        self.hs_b_min.setObjectName("hs_b_min")
        self.gridLayout.addWidget(self.hs_b_min, 2, 1, 1, 1)
        self.lb_b = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_b.setObjectName("lb_b")
        self.gridLayout.addWidget(self.lb_b, 2, 0, 1, 1)
        self.lb_v = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_v.setObjectName("lb_v")
        self.gridLayout.addWidget(self.lb_v, 3, 0, 1, 1)
        self.lb_max = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_max.setMaximumSize(QtCore.QSize(16777215, 12))
        self.lb_max.setObjectName("lb_max")
        self.gridLayout.addWidget(self.lb_max, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.lb_min.setText(_translate("MainWindow", "Minimum"))
        self.lb_r.setText(_translate("MainWindow", "Rouge"))
        self.pb_submit.setText(_translate("MainWindow", "Tester"))
        self.pb_enter.setText(_translate("MainWindow", "Valider"))
        self.lb_b.setText(_translate("MainWindow", "Bleu"))
        self.lb_v.setText(_translate("MainWindow", "Vert"))
        self.lb_max.setText(_translate("MainWindow", "Maximum"))

